#!/bin/bash
set -euo pipefail
set -vx

echo "installing Rosetta..."
sudo softwareupdate --install-rosetta

echo "moving dotfiles for chezmoi..."
[[ -d ~/.local/share ]] || mkdir -p ~/.local/share
[[ -L ~/.local/share/chezmoi ]] || ln -sf ~/.dotfiles ~/.local/share/chezmoi

echo "setting up .Brewfile..."
brew install chezmoi
chezmoi init
chezmoi apply ~/.Brewfile
