#!/bin/bash
set -euo pipefail
set -vx

echo "installing Rosetta..."
/usr/bin/pgrep -q oahd || sudo softwareupdate --install-rosetta

echo "moving dotfiles for chezmoi..."
[[ -d ~/.local/share ]] || mkdir -p ~/.local/share
[[ -d ~/.local/share/chezmoi ]] || mv ~/.dotfiles ~/.local/share/chezmoi

echo "setting up .Brewfile..."
brew install chezmoi
chezmoi init
chezmoi apply ~/.Brewfile
