#!/usr/bin/env bash

chezmoi apply

asdf plugin add java
asdf install java latest:temurin-21
asdf global java latest:temurin-21

asdf plugin add kotlin
asdf install kotlin latest
asdf global kotlin latest

asdf plugin add nodejs
asdf install nodejs latest:20
asdf global nodejs latest:20

asdf plugin add python
asdf install python latest
asdf global python latest

asdf plugin add quarkus
asdf install quarkus latest
asdf global quarkus latest
